# Generated by Django 3.0.7 on 2020-06-23 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(20)], verbose_name='Peso')),
                ('body_fat_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4)], verbose_name='Percentual de gordura')),
                ('front_photo', models.ImageField(blank=True, null=True, upload_to='body_front_photos', verbose_name='Foto frontal')),
                ('back_photo', models.ImageField(blank=True, null=True, upload_to='body_back_photos', verbose_name='Foto traseira')),
                ('side_photo', models.ImageField(blank=True, null=True, upload_to='body_side_photos', verbose_name='Foto lateral')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
