# Generated by Django 3.0.7 on 2020-06-25 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasures',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)], verbose_name='Peso'),
        ),
    ]
