# Generated by Django 3.0.7 on 2020-06-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female')], max_length=10, verbose_name='Gênero'),
        ),
    ]
