# Generated by Django 3.0.7 on 2020-06-22 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_progress', '0002_auto_20200622_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasures',
            name='back_photo',
            field=models.ImageField(upload_to='body_back_photos', verbose_name='Foto traseira'),
        ),
        migrations.AlterField(
            model_name='bodymeasures',
            name='body_fat_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4)], verbose_name='Percentual de gordura'),
        ),
        migrations.AlterField(
            model_name='bodymeasures',
            name='front_photo',
            field=models.ImageField(upload_to='body_front_photos', verbose_name='Foto frontal'),
        ),
        migrations.AlterField(
            model_name='bodymeasures',
            name='side_photo',
            field=models.ImageField(upload_to='body_side_photos', verbose_name='Foto lateral'),
        ),
    ]
