# Generated by Django 3.0.7 on 2020-06-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('body_progress', '0003_auto_20200622_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasures',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
